In [3]:
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
y = np.array([0,0,1,0,1,0,0,0,0,0,1,1,1,0,1,0,1,1,1,1])

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=10)

In [6]:
x_train

array([ 9,  6, 14,  4,  3, 12, 11, 19, 18,  8,  5, 16,  7, 10, 17, 15])

In [13]:
x_train

array([ 9,  6, 14,  4,  3, 12, 11, 19, 18,  8,  5, 16,  7, 10, 17, 15])

In [14]:
x_test

array([13,  2,  1, 20])

In [15]:
print("Training Features:", x_train)
print("Testing Features:", x_test)
print("Training Labels:", y_train)
print("Testing Labels:", y_test)

Training Features: [ 9  6 14  4  3 12 11 19 18  8  5 16  7 10 17 15]
Testing Features: [13  2  1 20]
Training Labels: [0 0 0 0 1 1 1 1 1 0 1 0 0 0 1 1]
Testing Labels: [1 0 0 1]
